version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  static:
    image: natdarke/robot-service-static
    ports: 
      - "5003:80"
    environment:
      - environment/prod/robot-service-static.env
  robot-site:
    image: natdarke/robot-service-front-end
    env_file:
      - environment/prod/robot-service-front-end.env
    ports:
      - "5000:3000"
    depends_on:
      - contentful-cache
      - static
  mysql:
    image: mysql:5.7.18
    env_file:
      - environment/prod/mysql.env
    ports:
      - "5002:3306"
  contentful-cache:
    image: natdarke/robot-service-contentful-cache
    env_file:
      - environment/prod/robot-service-contentful-cache.env
    ports:
      - "5001:80"
    depends_on:
      - mysql
